### ISSUE TITLE
Create backend for module

### ISSUE THREAD

**Issue by RicardoJ** [Sproutwise/magento#1]
**Requirements:**

A easy to use and configurable payment module backend.

**Tasks:**

- [ ] Split payment methods in different files
- [ ] Add branding logo in backend
- [ ] Add module information in backend

**Optional tasks:**
(These are optional tasks and are not required to finish the milestone).

- [ ] Set ACL
- [ ] Create API for Magento
