### ISSUE TITLE
Create models for payment methods

### ISSUE THREAD

**Issue by RicardoJ** [Sproutwise/magento#2]
**Requirements:**

Payment methods models should extend a core model. This should be usable by the GatewayInterface.

**Tasks:**

- [ ] Create payment methods
- [ ] Give backend better intial payment names
- [ ] Develop the GatewayInterface

**Optional tasks:**

There are no optional tasks defined.
