### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by RicardoJ** [Sproutwise/magento#3]
**Requirements:**

This module should be have tests. That way Travis CI can be sure that whenever we develop new features or fix bugs, they work before we deploy a new version.

**Tasks:**

- [ ] Create connection between TravisCI and this repository.
- [ ] Create `.travis.yml` file and other files eg. `bootstrap.php`.
- [ ] Hook `bootstrap.php` with the Magento Test Framework

**Optional tasks:**

There are no optional tasks defined.
